name: crud
description: "A new Flutter project."

version: 1.0.0+1

environment:
  sdk: ^3.6.2

dependencies:
  flutter:
    sdk: flutter
  cloud_firestore: ^5.6.5
  firebase_core: ^3.12.1
  firebase_auth: ^5.5.1
  firebase_storage: ^12.4.5
  file_picker: ^10.1.9
  cupertino_icons: ^1.0.8
  permission_handler: ^11.4.0
  flutter_background_messenger: ^0.0.2
  http: ^1.4.0
  flutter_launcher_icons: ^0.14.4

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_localizations:
    sdk: flutter
  intl: ^0.19.0

flutter:
  uses-material-design: true

flutter_icons:
  android: true
  ios: true
  remove_alpha_ios: true
  image_path: "assets/images/icone.png"
  min_sdk_android: 23
  adaptive_icon_background: "#ffffff"